name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Compile and Run Tests
      run: |
        mkdir -p out
        javac -cp "$GITHUB_WORKSPACE/libs/*:$GITHUB_WORKSPACE/libs/JUnit5/*:$GITHUB_WORKSPACE/src/main/java:$GITHUB_WORKSPACE/src/test/java" -d out $GITHUB_WORKSPACE/src/main/java/com/eazydeals/**/*.java $GITHUB_WORKSPACE/src/test/java/com/eazydeals/**/*.java
        find out -name "*.class"
        java -XX:+EnableDynamicAgentLoading -cp "$GITHUB_WORKSPACE/out:$GITHUB_WORKSPACE/libs/*:$GITHUB_WORKSPACE/libs/JUnit5/*" org.junit.platform.console.ConsoleLauncher --select-class com.eazydeals.servlets.ChangePasswordServletTest --class-path $GITHUB_WORKSPACE/out --details verbose
        
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/TEST-*.xml'
