name: eazydeals-github-workflow

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - feature/github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: List contents of libs directory
      run: ls -R EazyDeals/libs
      continue-on-error: true

    - name: Compile Java source files
      run: |
        mkdir -p out
        javac -cp "EazyDeals/libs/*:EazyDeals/src/main/java" -d out EazyDeals/src/main/java/com/eazydeals/**/*.java

    - name: Compile Test Java files
      run: |
        javac -cp "EazyDeals/libs/*:EazyDeals/src/main/java:EazyDeals/src/test/java:out" -d out EazyDeals/src/test/java/com/eazydeals/**/*.java

    - name: Run all tests
      run: |
        java -cp "out:EazyDeals/libs/*:EazyDeals/src/test/java" org.junit.runner.JUnitCore $(find EazyDeals/src/test/java -name "*Test.java" | sed 's/.*java\///' | sed 's/\.java//' | sed 's/\//./g')

    - name: Package Java application
      run: |
        jar cvf eazydeals.jar -C out .

    - name: Upload Jar file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: eazydeals-jar
        path: eazydeals.jar
