name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set environment variables for database
      run: |
        echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        
    - name: Compile
      run: |
        mkdir -p out
        javac -cp "$GITHUB_WORKSPACE/libs/*:$GITHUB_WORKSPACE/libs/JUnit5/*:$GITHUB_WORKSPACE/libs/mockito-inline-4.0.0.jar:$GITHUB_WORKSPACE/src/main/java:$GITHUB_WORKSPACE/src/test/java" -d out $GITHUB_WORKSPACE/src/main/java/com/eazydeals/**/*.java $GITHUB_WORKSPACE/src/test/java/com/eazydeals/**/*.java
        find out -name "*.class"

    - name: Run Tests
      run: |
        java -XX:+EnableDynamicAgentLoading --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -cp "$GITHUB_WORKSPACE/out:$GITHUB_WORKSPACE/libs/*:$GITHUB_WORKSPACE/libs/JUnit5/*:$GITHUB_WORKSPACE/libs/mockito-inline-4.0.0.jar" org.junit.platform.console.ConsoleLauncher --select-class com.eazydeals.servlets.LogoutServletTest --class-path $GITHUB_WORKSPACE/out --details verbose
