name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Compile and Run Tests
      run: |
        mkdir -p out
        javac -cp "libs/*:libs/JUnit5/*:src/main/java:src/test/java" -d out src/main/java/com/eazydeals/**/*.java src/test/java/com/eazydeals/**/*.java
        java -XX:+EnableDynamicAgentLoading -cp "out:libs/:libs/JUnit5/" org.junit.platform.console.ConsoleLauncher --select-class com.eazydeals.servlets.LogoutServletTest --class-path out --details verbose

        

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/TEST-*.xml'
